name: Microsoft Teams Deploy Card
author: Project Toko Bifrost
description: Notify your Teams channel with a beautiful, comprehensive deployment card
branding:
  icon: bell
  color: purple

inputs:
  webhook-uri:
    description: Microsoft Teams webhook URI
    required: true
  github-token:
    description: Github token
    required: true
  allowed-file-len:
    description: Allowed number of files to display
    required: false
    default: 7
  timezone:
    description: Timezone for notification
    required: false
    default: UTC
  layout:
    description: Card layout (i.e. "complete", "cozy", "compact")
    required: true
    default: complete
  include-files:
    description: Only for complete layout; Set false to exclude list of files
    required: false
    default: true

runs:
  using: node12
  main: dist/main/index.js
