name: Microsoft Teams Deploy Card
author: Project Toko Bifrost
description: Notify your Teams channel with a beautiful, comprehensive deployment card
branding:
  icon: bell
  color: purple

inputs:
  webhook-uri:
    description: Microsoft Teams webhook URI
    required: true
  github-token:
    description: Github token
    required: true
  environment:
    description: Name of the environment (won't be included in the card if none)
    required: false
    default: null
  timezone:
    description: Timezone for notification
    required: false
    default: UTC
  card-layout-start:
    description: Card layout on start (i.e. "complete", "cozy", "compact")
    required: false
    default: complete
  card-layout-exit:
    description: Card layout on end (i.e. "complete", "cozy", "compact")
    required: false
    default: compact
  show-on-start:
    description: Show the MS Teams card upon starting this Github Actions job
    required: false
    default: true
  show-on-exit:
    description: Show the MS Teams card upon exiting this Github Actions job
    required: false
    default: true
  include-files:
    description: Only for complete layout; Set false to exclude list of files
    required: false
    default: true
  allowed-file-len:
    description: Allowed number of files to display
    required: false
    default: 7

runs:
  using: node12
  main: dist/main/index.js
  post: dist/post/index.js
