name: MS Teams Deploy Card

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          environment: Development
          timezone: Australia/Sydney
          card-layout-start: cozy
          include-files: true

      - run: echo Success
      - run: echo Success
      - run: echo Success
      - run: echo Success
      - run: echo Success
      - run: exit 1
