name: MS Teams Deploy Card

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          environment: Development
          timezone: Australia/Sydney
          card-layout-start: cozy
          show-on-failure: true

      - run: exit 1

      - run: exit 0
